# Generated by Django 2.0.5 on 2018-05-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaInicio',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaTermino',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
