# Generated by Django 2.0.5 on 2018-05-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180526_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fechaTermino',
        ),
    ]
