# Generated by Django 2.0.5 on 2018-05-27 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180526_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaInicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaTermino',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
